name: Create issue

# githubのissueが開かれたときに作動(type->[opend])
on:
  issues:
  push:
    types: [opened]

# ここからworkflow
jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    if: github.event.action == 'opened'
    steps:
    - name: Create Jira Issue
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
          -d '{
            "fields": {
              "project": {
                "key": "KWI"
              },
              "issuetype": {
                "name": "Task"
              },
              "summary": "${{ github.event.issue.title }}",
              "description": "${{ github.event.issue.body }}",
              "labels": [
                "github-issues",
                "github-issue-#${{ github.event.issue.number }}"
              ]
            }
          }' \
          ${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/
