name: Create issue

# githubのissueが開かれたときに作動(type->[opend])
on:
  issues:
  push:
    types: [opened]

# ここからworkflow
jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    if: github.event.action == 'opened'
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"

    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: KWI
        issuetype: Task
        # issuesのタイトルが要約になるように設定
        summary: ${{github.event.issue.title }}
        # issuesの本文が説明になるように設定
        description: ${{ github.event.issue.body }}
